import PDFDocument from "pdfkit";

export const generateInvoicePDF = ({
  billId,
  shopName,
  shopAddress,
  shopPhone,
  customerName,
  customerEmail,
  paymentMethod,
  items = [],
  totalAmount = 0,
  date,
}) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50 });

      const buffers = [];
      doc.on("data", (data) => buffers.push(data));
      doc.on("end", () => resolve(Buffer.concat(buffers)));

      /* HEADER */

      doc
        .fontSize(22)
        .font("Helvetica-Bold")
        .text(shopName || "ISMA Billing System", { align: "center" });

      doc.moveDown(0.3);

      doc
        .fontSize(10)
        .font("Helvetica")
        .text(shopAddress || "Store Address", { align: "center" });

      doc.text(`Phone: ${shopPhone || "-"}`, { align: "center" });

      doc.moveDown(1.5);

      /* TITLE */

      doc
        .fontSize(18)
        .font("Helvetica-Bold")
        .text("INVOICE", { align: "center" });

      doc.moveDown(1);

      /* DETAILS */

      const invoiceDate = date || new Date().toLocaleDateString("en-IN");

      doc
        .fontSize(11)
        .font("Helvetica")
        .text(`Invoice ID: ${billId || "-"}`)
        .text(`Date: ${invoiceDate}`)
        .text(`Customer: ${customerName || "Walk-in Customer"}`)
        .text(`Email: ${customerEmail || "-"}`)
        .text(`Payment Method: ${paymentMethod || "Cash"}`);

      doc.moveDown(1.5);

      /* TABLE */

      const itemX = 50;
      const qtyX = 300;
      const priceX = 370;
      const totalX = 450;

      doc.font("Helvetica-Bold");

      doc.text("Product", itemX);
      doc.text("Qty", qtyX);
      doc.text("Unit Price", priceX);
      doc.text("Total", totalX);

      doc.moveDown();

      doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();

      doc.moveDown(0.5);

      doc.font("Helvetica");

      let calculatedTotal = 0;

      if (items.length === 0) {
        doc.text("No items available", itemX);
      } else {
        items.forEach((item) => {
          const y = doc.y;

          const name = item?.name || "-";
          const qty = item?.quantity || 0;

          const unitPrice =
            item?.priceINR ??
            item?.unitPrice ??
            item?.price ??
            0;

          const total =
            item?.totalPrice ??
            qty * unitPrice;

          calculatedTotal += total;

          doc.text(name, itemX, y);
          doc.text(qty.toString(), qtyX, y);
          doc.text(`₹${unitPrice}`, priceX, y);
          doc.text(`₹${total}`, totalX, y);

          doc.moveDown();
        });
      }

      doc.moveDown();

      doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();

      doc.moveDown(1);

      /* TOTAL */

      const finalTotal = totalAmount || calculatedTotal;

      doc
        .font("Helvetica-Bold")
        .fontSize(14)
        .text(`Grand Total: ₹${finalTotal}`, {
          align: "right",
        });

      doc.moveDown(2);

      /* FOOTER */

      doc
        .font("Helvetica")
        .fontSize(11)
        .text("Thank you for shopping with us!", {
          align: "center",
        });

      doc.moveDown(0.5);

      doc
        .fontSize(9)
        .fillColor("gray")
        .text("Generated by ISMA Billing System", {
          align: "center",
        });

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
};